# Generated by Django 3.0.4 on 2021-05-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_blogmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='category',
            field=models.CharField(choices=[('life', '生活'), ('bussiness', 'ビジネス'), ('other', 'その他')], max_length=50),
        ),
    ]
